spring.application.name=demo

# Server settings
server.port=8080

# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/university_db
spring.datasource.username=postgres
# Here I used an environment variable 
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate Settings
# 'update' will create tables if they don't exist and keep your data safe
# 'create' will drop and recreate tables on each run
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Postgres-specific dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Disable H2 Console as it's no longer needed
spring.h2.console.enabled=false

spring.security.user.name=admin
spring.security.user.password=password123