//this is the user repository interface that will be used to interact with the database to perform CRUD operations on the user entity and we will implement this interface later using Spring Data JPA to create a repository for the user entity that will allow us to perform CRUD operations on the user entity without having to write any SQL queries and we will also use this repository to find a user by email for authentication purposes.
package com.uni.demo.security.user;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Optional;

public interface UserRepository extends JpaRepository<User, Integer> { //to extend the JpaRepository interface which is a Spring Data JPA interface that provides CRUD operations for the user entity and we will specify the type of the entity and the type of the primary key
    Optional<User> findByEmail(String email); //a method to find a user by email "because it is unique" for authentication purposes and we will implement this method later using Spring Data JPA to create a query method that will allow us to find a user by email without having to write any SQL queries

}
//the first thing that will intercept the HTTP request is the security filter "JWT authentication filter" chain that will check if the request is authenticated or not and if it is authenticated it will check if the user has the required role to access the requested resource and if the user is not authenticated it will return a 401 Unauthorized response and if the user is authenticated but does not have the required role it will return a 403 Forbidden response and if the user is authenticated and has the required role it will allow the request to proceed to the next filter in the chain which will be the authentication filter that will authenticate the user using JWT (JSON Web Token) and then it will allow the request to proceed to the next filter in the chain which will be the authorization filter that will authorize the user based on their roles and permissions and then it will allow the request to proceed to the next filter in the chain which will be the controller that will handle the request and return a response.
//So now we will implement JwtAuthenticationFilter.java that will be responsible for authenticating the user using JWT (JSON Web Token) and then we will implement JwtAuthorizationFilter.java that will be responsible for authorizing the user based on their roles and permissions and then we will implement SecurityConfig.java that will be responsible for configuring the security of our application and then we will implement AuthController.java that will be responsible for handling the authentication and authorization requests and then we will implement UserService.java that will be responsible for handling the business logic related to the user entity and then we will implement UserRepository.java that will be responsible for interacting with the database to perform CRUD operations on the user entity.